---
title: "QC ImpulseDE2"
author: "Nicole Gay"
date: "6/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/oak/stanford/groups/smontgom/nicolerg/src/MOTRPAC/ImpulseDE2/R/')
library(compiler)
library(Biobase)
library(BiocParallel)
library(circlize)
library(ComplexHeatmap)
library(cowplot)
library(DESeq2)
library(ggplot2)
library(grDevices)
library(knitr)
library(Matrix)
library(methods)
library(stats)
library(SummarizedExperiment)
library(utils)
library(olsrr)
```

## Source my edited version of ImpulseDE2
```{r source functions}
for(f in list.files()){
  print(f)
  source(f)
}
```

## Starting point - simulated data 
```{r simulate data}
# case-only with batch effects
lsSimulatedData <- simulateDataSetImpulseDE2(
  vecTimePointsA   = rep(seq(1,8),4),
  vecTimePointsB   = NULL,
  vecBatchesA      = c(rep(1,15), rep(2,17)),
  vecBatchesB      = NULL,
  scaNConst        = 30,
  scaNImp          = 50,
  scaNLin          = 10,
  scaNSig          = 30,
  scaMuBatchEffect = 3,
  scaSDBatchEffect = 0.2,
  dirOutSimulation = NULL)

```

## Scenario 1: only covariates (no batch effects); two betas
```{r adjust df}
dfAnnotation = lsSimulatedData$dfAnnotation
matCounts = lsSimulatedData$matObservedCounts
dim(matCounts)
dfAnnotation
# call "Batch" something else
colnames(dfAnnotation)[colnames(dfAnnotation) == 'Batch'] = 'sample_batch'
# add sex covariate
dfAnnotation$sex = sample(c('male','female'), replace=TRUE, size=nrow(dfAnnotation))
# add continuous covariate
dfAnnotation$num_var = rnorm(nrow(dfAnnotation))
head(dfAnnotation)
table(dfAnnotation$Time, dfAnnotation$sample_batch)
```

```{r add confounder, eval=F}
dfAnnotation$var1 = ifelse(dfAnnotation$sex == 'female', 5, 10)
```

```{r add collinear cov, eval=T}
f = rnorm(nrow(dfAnnotation[dfAnnotation$sex =='female',]), 5, 0.5)
m = rnorm(nrow(dfAnnotation[dfAnnotation$sex == 'male',]), 10, 1)
dfAnnotation$var1[dfAnnotation$sex == 'female'] = f
dfAnnotation$var1[dfAnnotation$sex == 'male'] = m
```

```{r set params}
matCountData = matCounts
boolCaseCtrl = FALSE
vecCovFactor = c('sample_batch','sex')
vecCovContinuous = c('num_var', 'var1')
scaNProc = 1
boolVerbose = TRUE
boolBeta2 = TRUE
scaQThres = NULL
vecSizeFactorsExternal = NULL
vecDispersionsExternal = NULL
boolIdentifyTransients = TRUE 
boolVerbose = TRUE
MAXIT = 1000
```

## Check to see if covariates affect dispersions
```{r deseq dispersions, eval=F}
dds1 <- DESeqDataSetFromMatrix(
    countData = matCountData,
    colData = dfAnnotation,
    design = ~ Time)
dds1 <- estimateSizeFactors(dds1)
dds1 <- estimateDispersions(dds1)

dds2 <- DESeqDataSetFromMatrix(
    countData = matCountData,
    colData = dfAnnotation,
    design = ~ 1)
dds2 <- estimateSizeFactors(dds2)
dds2 <- estimateDispersions(dds2)

dispersions(dds1) == dispersions(dds2)
```

# Walk through main function, step by step 
```{r process data}
strMessage <- paste0("ImpulseDE2 for count data, v", 
                     packageDescription("ImpulseDE2", fields = "Version"))
if (boolVerbose) { message(strMessage) }
strReport <- strMessage

# 1. Process input data
strMessage <- "# Process input"
if (boolVerbose) { message(strMessage) }
strReport <- paste0(strReport, "\n", strMessage)
# Extract count matrix if handed SummarizedExperiment
if (class(matCountData) == "SummarizedExperiment"){ 
    matCountData <- assay(matCountData)
}
lsProcessedData <- processData(
    dfAnnotation = dfAnnotation, 
    matCountData = matCountData, 
    boolCaseCtrl = boolCaseCtrl, 
    boolBeta2 = boolBeta2,
    vecCovFactor = vecCovFactor, 
    vecCovContinuous = vecCovContinuous,
    vecDispersionsExternal = vecDispersionsExternal, 
    vecSizeFactorsExternal = vecSizeFactorsExternal)

matCountDataProc <- lsProcessedData$matCountDataProc
dfDESeqAnnotationProc <- lsProcessedData$dfDESeqAnnotationProc
lsdfCovProc <- lsProcessedData$lsdfCovProc
vecSizeFactorsExternalProc <- 
    lsProcessedData$vecSizeFactorsExternalProc
vecDispersionsExternalProc <- 
    lsProcessedData$vecDispersionsExternalProc
if (boolVerbose) { 
    write(lsProcessedData$strReportProcessing, file = "", ncolumns = 1)
}
strReport <- paste0(strReport, lsProcessedData$strReportProcessing)
```

```{r check processed data }
# look at a few things 
head(lsProcessedData$dfDESeqAnnotationProc)
names(head(lsProcessedData$lsdfCovProc)) # lsdfCovProc is a new addition
head(lsProcessedData$lsdfCovProc$case)
head(lsProcessedData$lsdfCovProc$control)
```

```{r DESeq2}
# 2. Run DESeq2 Use dispersion factors from DESeq2 if
if (is.null(vecDispersionsExternal)) {
    strMessage <- paste0("# Run DESeq2: Using dispersion factors",
                         "computed by DESeq2.")
    if (boolVerbose) { message(strMessage) }
    strReport <- paste0(strReport, "\n", strMessage)
    tm_runDESeq2 <- system.time({
        vecDispersions <- runDESeq2(
            dfAnnotationProc = dfDESeqAnnotationProc, 
            matCountDataProc = matCountDataProc, 
            boolCaseCtrl = boolCaseCtrl, 
            vecCovFactor = vecCovFactor,
            vecCovContinuous = vecCovContinuous)
    })
    strMessage <- paste0("Consumed time: ", 
                         round(tm_runDESeq2["elapsed"]/60,2), " min.")
    if (boolVerbose) { message(strMessage) }
    strReport <- paste0(strReport, "\n", strMessage)
} else {
    # Use externally provided dispersions and reorder
    strMessage <- "# Using externally supplied dispersion factors."
    if (boolVerbose) { message(strMessage) }
    strReport <- paste0(strReport, "\n", strMessage)
    vecDispersions <- vecDispersionsExternalProc
}

# 3. Compute size factors
strMessage <- "# Compute size factors"
if (boolVerbose) { message(strMessage) }
strReport <- paste0(strReport, "\n", strMessage)
vecSizeFactors <- computeNormConst(
    matCountDataProc = matCountDataProc, 
    vecSizeFactorsExternal = vecSizeFactorsExternalProc)
```

```{r create instance}
# 4. Create instance of ImpulseDE2Object Create ImpulseDE2 object
objectImpulseDE2 <- new(
    "ImpulseDE2Object", 
    dfImpulseDE2Results = NULL, 
    vecDEGenes = NULL, 
    lsModelFits = NULL, 
    matCountDataProc = matCountDataProc, 
    vecAllIDs = rownames(matCountData), 
    dfDESeqAnnotationProc = dfDESeqAnnotationProc, 
    lsdfCovProc = lsdfCovProc,
    vecSizeFactors = vecSizeFactors, 
    vecDispersions = vecDispersions, 
    boolCaseCtrl = boolCaseCtrl, 
    boolBeta2 = boolBeta2,
    vecCovFactor = vecCovFactor, 
    vecCovContinuous = vecCovContinuous,
    scaNProc = scaNProc, 
    scaQThres = scaQThres, 
    strReport = strReport)
```

```{r check new things}
names(get_lsdfCovProc(objectImpulseDE2))
head(get_lsdfCovProc(objectImpulseDE2)$case)
head(get_dfDESeqAnnotationProc(objectImpulseDE2))
get_vecCovContinuous(objectImpulseDE2)
get_vecCovFactor(objectImpulseDE2)
```

```{r fit null and alt for each gene}
# 5. Fit null and alternative model to each gene
objectImpulseDE2 <- fitModels(
    objectImpulseDE2 = objectImpulseDE2, 
    vecCovFactor = vecCovFactor,
    vecCovContinuous = vecCovContinuous, 
    boolCaseCtrl = boolCaseCtrl,
    boolBeta2 = boolBeta2,
    MAXIT = MAXIT)
```




```{r processData}
objectImpulseDE2 = runImpulseDE2(
    matCountData = matCountData, 
    dfAnnotation = dfAnnotation, 
    boolCaseCtrl = FALSE,
    boolBeta2 = TRUE,
    boolIdentifyTransients = TRUE,
    vecCovFactor = vecCovFactor,
    vecCovContinuous = vecCovContinuous,
    scaNProc = 1,
    MAXIT = 5000) 
modelFits = get_lsModelFits(obj=objectImpulseDE2)
modelFits$case$gene71$lsImpulseFit$vecImpulseParam

withCov = runImpulseDE2(
    matCountData = matCountData, 
    dfAnnotation = dfAnnotation, 
    boolCaseCtrl = FALSE,
    boolBeta2 = TRUE,
    boolIdentifyTransients = TRUE,
    vecConfounders = vecConfounders,
    vecCovariates = vecCovariates,
    scaNProc = 1,
    MAXIT = 5000) 
modelFits = get_lsModelFits(obj=withCov)
modelFits$case$gene71$lsImpulseFit$vecImpulseParam

singleBeta = runImpulseDE2(
    matCountData = matCountData, 
    dfAnnotation = dfAnnotation, 
    boolCaseCtrl = FALSE,
    boolBeta2 = FALSE,
    boolIdentifyTransients = TRUE,
    vecConfounders = vecConfounders,
    vecCovariates = NULL,
    scaNProc = 1,
    MAXIT = 5000) 
modelFits = get_lsModelFits(obj=singleBeta)
modelFits$case$gene71$lsImpulseFit$vecImpulseParam

lsgplotsGenes <- plotGenes(
  vecGeneIDs       = objectImpulseDE2$dfImpulseDE2Results[dfres$isTransient == TRUE, "Gene"],
  #scaNTopIDs       = 10,
  objectImpulseDE2 = objectImpulseDE2,
  boolCaseCtrl     = FALSE,
  dirOut           = NULL,
  strFileName      = NULL,
  vecRefPval       = NULL, 
  strNameRefMethod = NULL)
print(lsgplotsGenes[[1]])

lsgplotsGenes <- plotGenes(
  vecGeneIDs       = "gene71",
  #scaNTopIDs       = 10,
  objectImpulseDE2 = withCov,
  boolCaseCtrl     = FALSE,
  dirOut           = NULL,
  strFileName      = NULL,
  vecRefPval       = NULL, 
  strNameRefMethod = NULL)
print(lsgplotsGenes[[1]])

lsgplotsGenes <- plotGenes(
  vecGeneIDs       = "gene71",
  #scaNTopIDs       = 10,
  objectImpulseDE2 = singleBeta,
  boolCaseCtrl     = FALSE,
  dirOut           = NULL,
  strFileName      = NULL,
  vecRefPval       = NULL, 
  strNameRefMethod = NULL)
print(lsgplotsGenes[[1]])
```

```{r look at output}
dfres = objectImpulseDE2$dfImpulseDE2Results
head(dfres)

objectImpulseDE2$dfImpulseDE2Results

objectImpulseDE2$dfImpulseDE2Results["gene40",]
objectImpulseDE2$dfImpulseDE2Results[objectImpulseDE2$dfImpulseDE2Results$isTransient==TRUE,]
modelFits = get_lsModelFits(obj=objectImpulseDE2)
names(modelFits)
names(modelFits$case)
modelFits$case$gene40

lsgplotsGenes <- plotGenes(objectImpulseDE2, 
  #vecGeneIDs       = dfres[dfres$isTransient == TRUE, "Gene"],
  scaNTopIDs       = 10,
  objectImpulseDE2 = objectImpulseDE2,
  boolCaseCtrl     = FALSE,
  dirOut           = NULL,
  strFileName      = NULL,
  vecRefPval       = NULL, 
  strNameRefMethod = NULL)
print(lsgplotsGenes[[5]])

c(1, exp(c(0,0):(9)))
```